language: python
python: 2.7
env:
- TOX_ENV=py26
- TOX_ENV=py27
- TOX_ENV=pep8

install:
- pip install -v tox
- pip install -v -e git://github.com/rackerlabs/ironic.git@0a455ccd67d4d709720fa354adebfdccd14ea5a8#egg=ironic

script:
- tox -vvv -e $TOX_ENV

notifications:
  irc:
    channels:
      - "chat.freenode.net#teeth-dev"
    use_notice: true
    skip_join: true
  email: false
